patch -p0 < grpc_channel.patch
patch -p0 < mpi_msg.patch
patch -p0 < mpi_rendezvous_mgr.patch
patch -p0 < mpi_utils.patch
patch -p0 < BUILD.patch
patch -p0 < master_session.patch
patch -p0 < mpi_rendezvous_mgr2.patch
patch -p0 < mpi_utils2.patch
patch -p0 < worker_proto.patch
